# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-22 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import draceditor.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='post', verbose_name='Foto Image', width_field='width_field')),
                ('height_field', models.IntegerField(default=0, verbose_name='Wysokość')),
                ('width_field', models.IntegerField(default=0, verbose_name='Szerokość')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('text', draceditor.models.DraceditorField(verbose_name='Treść')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Odnośnik')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Strona')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tag')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
