# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-22 17:07
from __future__ import unicode_literals

import blogplus.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', blogplus.fields.ThumbnailImageField(upload_to='foto')),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.Galeria'),
        ),
    ]
