# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20170222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
